version: '3.7'

services:

  postgres:
    image: postgres
    restart: always
    container_name: pgFacturacion
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: facturacion
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data-postgres:/var/lib/postgresql/data